apiVersion: v1
kind: Service
metadata:
  name: phpservice
spec:
  selector:
    env: dev
    dc: IN
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpservice
spec:
  selector:
    matchLabels:
      env: dev
      dc: IN
  template:
    metadata:
      labels:
        env: dev
        dc: IN
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: php
        ports:
        - containerPort: 80
        volumeMounts:
        - name: phpvol
          mountPath: /var/www/html
      volumes:
      - name: phpvol
        persistentVolumeClaim:
          claimName: phpclaim
